# Generated by Django 2.0.1 on 2018-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_description',
            field=models.TextField(default='description'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
