# Generated by Django 2.0.1 on 2018-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180206_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='sell_name',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
