# Generated by Django 2.0.1 on 2018-02-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180206_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_name',
            field=models.CharField(max_length=200),
        ),
    ]
