# Generated by Django 2.0.1 on 2018-02-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180206_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='sell',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
