# Generated by Django 2.0.1 on 2018-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro_cidade', models.CharField(max_length=200)),
                ('bairro_cidade', models.CharField(max_length=200)),
                ('nome_cidade', models.CharField(max_length=200)),
                ('estado_cidade', models.CharField(max_length=200)),
                ('cep_cidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='local',
        ),
    ]
