# Generated by Django 2.0.1 on 2018-02-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20180221_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='bairro_cidade',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='cep_cidade',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='estado_cidade',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='logradouro_cidade',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='nome_cidade',
            new_name='nome',
        ),
    ]
