# Generated by Django 2.0.2 on 2018-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20180221_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='complemento',
            field=models.CharField(default='complemento', max_length=200),
        ),
    ]
